=== stefyxx/XML/XML/exo_cv.dtd
<!ELEMENT cv (titre, cvnom, etatcivil, formations, connaissances, professionnel)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT cvnom (#PCDATA)>
<!ELEMENT etatcivil (nom, prenom, naissance, situation, adresse?, code_postal?, ville?, pays?, telephone?, email?,caracteristiques?)>
<!ELEMENT caracteristiques (caracteristique+)>
<!ELEMENT formations (formation+)>
<!ELEMENT connaissances (technique*, langue*)>
<!ELEMENT professionnel (experience+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT naissance (#PCDATA)>
<!ELEMENT situation (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT code_postal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT caracteristique (#PCDATA)>
<!ATTLIST caracteristique
    type CDATA #REQUIRED>
<!ELEMENT formation EMPTY>
<!ATTLIST formation
    date-iso CDATA #REQUIRED
    date CDATA #REQUIRED
    datefin CDATA #IMPLIED
    intitule CDATA #REQUIRED
    description CDATA #IMPLIED>
<!ELEMENT technique EMPTY>
<!ATTLIST technique
    type (0 | 1 | 2| 3 | 4 | 5) #REQUIRED
    nom CDATA #REQUIRED
    description CDATA #IMPLIED>
<!ELEMENT langue EMPTY>
<!ATTLIST langue
    nom CDATA #REQUIRED
    niveau CDATA #REQUIRED>
<!ELEMENT experience (missions, environnement)>
<!ATTLIST experience
    date-iso CDATA #REQUIRED
    date CDATA #REQUIRED
    datefin CDATA #IMPLIED
    client CDATA #IMPLIED
    entreprise CDATA #REQUIRED
    fonction CDATA #REQUIRED>
    
<!ELEMENT environnement (technique+)>

<!ELEMENT missions (mission+)>
<!ELEMENT mission (#PCDATA)>

<!ELEMENT personnel (activite*)>
<!ELEMENT activite (#PCDATA)>
<!ATTLIST activite
    type CDATA #REQUIRED
    nom CDATA #REQUIRED
    description CDATA #IMPLIED>

=== stefyxx/XML/XML/exo_cv.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cv SYSTEM "exo_cv.dtd">
<cv>
    <titre>Monsieur</titre>
    <cvnom>Philippe STONS</cvnom>
    <etatcivil>
        <nom>STONS</nom>
        <prenom>Philippe</prenom>
        <naissance>top secret</naissance>
        <situation>tout le monde s'en moque</situation>
    </etatcivil>
    <formations>
        <formation date-iso="1900-01-01" date="Aujourd'hui" intitule="Ecole maternelle" />
    </formations>
    <connaissances />
    <professionnel>
        <experience date-iso="2000-09-01" date="Aujourd'hui" entreprise="UNS" fonction="Professeur">
            <missions>
                <mission>recherche</mission>
            </missions>
            <environnement>
                <technique type="5" nom="EPST" />
            </environnement>
        </experience>
    </professionnel>
</cv>
