=== stefyxx/XML/epreuve_XML_Mauti_Stefania/imbrication.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="./adresse.xsd"/>
<xsd:element name="Classe">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="Enleves">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Enleve" maxOccurs="12" minOccurs="6">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="nom" type="Nom"/>
                                    <xsd:element name="prenom" type="Prenom"/>
                                    <xsd:element name="dateNaissance" type="xsd:date"/>
                                    <xsd:element name="Email" type="Email"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Professeur" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="nom" type="Nom"/>
                        <xsd:element name="prenom" type="Prenom"/>
                        <xsd:element name="titre">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:enumeration value="Mr"/>
                                    <xsd:enumeration value="Mme"/>
                                    <xsd:enumeration value="Melle"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="anne" type="xsd:gYear"/>
                        <xsd:element name="adresse" type="Adresse"/>
                        <xsd:element name="n_telephone" type="xsd:string"/>
                        <xsd:element name="Email" type="Email"></xsd:element>
                        <xsd:element name="CoursDonne" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="titre">
                                        <xsd:simpleType>
                                            <xsd:restriction base="xsd:string">
                                                <xsd:minLength value="2"/>
                                                <xsd:maxLength value="255"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="nCredits">
                                        <xsd:simpleType>
                                            <xsd:restriction base="xsd:positiveInteger">
                                                <xsd:pattern value="[1-9]"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:simpleType name="Nom">
    <xsd:restriction base="xsd:string">
        <xsd:maxLength value="50"/>
        <xsd:minLength value="2"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="Prenom">
    <xsd:restriction base="xsd:string">
        <xsd:maxLength value="50"/>
        <xsd:minLength value="2"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="Email">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*"></xsd:pattern>
    </xsd:restriction>
</xsd:simpleType>

</xsd:schema>

=== stefyxx/XML/epreuve_XML_Mauti_Stefania/imbrications.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Classe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./imbrication.xsd">
    <Enleves>
        <Enleve>
            <nom>bla</nom>
            <prenom>bla</prenom>
            <dateNaissance>1976-12-30</dateNaissance>
            <Email>coGG@co.be</Email>
        </Enleve>
        <Enleve>
            <nom>bla</nom>
            <prenom>bla</prenom>
            <dateNaissance>1976-12-30</dateNaissance>
            <Email>coGG@co.be</Email>
        </Enleve>
        <Enleve>
            <nom>bla</nom>
            <prenom>bla</prenom>
            <dateNaissance>1976-12-30</dateNaissance>
            <Email>coGG@co.be</Email>
        </Enleve>
        <Enleve>
            <nom>bla</nom>
            <prenom>bla</prenom>
            <dateNaissance>1976-12-30</dateNaissance>
            <Email>coGG@co.be</Email>
        </Enleve>
        <Enleve>
            <nom>bla</nom>
            <prenom>bla</prenom>
            <dateNaissance>1976-12-30</dateNaissance>
            <Email>coGG@co.be</Email>
        </Enleve>
        <Enleve>
            <nom>bla</nom>
            <prenom>bla</prenom>
            <dateNaissance>1976-12-30</dateNaissance>
            <Email>coGG@co.be</Email>
        </Enleve>
    </Enleves>

    <Professeur>
        <nom>Jo</nom>
        <prenom>Jo</prenom>
        <titre>ooooo</titre>
        <anne>1992</anne>
        <adresse>
            <rue>blabla</rue>
            <numero>4</numero>
            <boite>5</boite>
            <code_postal>1000</code_postal>
            <ville>Bruxelles</ville>
        </adresse>
        <n_telephone>213654412</n_telephone>
        <Email>coGG@co.be</Email>
        <CoursDonne>
            <titre>lala</titre>
            <nCredits>5</nCredits>
        </CoursDonne>
        <CoursDonne>
            <titre>lala</titre>
            <nCredits>5</nCredits>
        </CoursDonne>
    </Professeur>
</Classe>
