=== stefyxx/XML/XML/biblio/biblio.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="books">
        <!-- scrivo 'books' perche poi posso scrivere 'book' e dire che ne posso avere piÃ¹ di 1 con maxOccurs -->
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="book" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>

    </xsd:element>

    <xsd:element name="book">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="title" type="xsd:string"/>
                <xsd:element ref="author"/>
                <xsd:element name="gender" type="xsd:string"></xsd:element>
                <xsd:element ref="pubDate"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="author">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="firstname" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:simpleType name="Day">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="31"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Month">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:maxInclusive value="12"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="pubDate">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Day" type="Day"></xsd:element>
                <xsd:element name="Month" type="Month"></xsd:element>

                <xsd:element name="Year" type="xsd:string"/>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== stefyxx/XML/XML/biblio/biblio.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--<!DOCTYPE books SYSTEM "exo1.dtd"> -->

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="./biblio.xsd">

    <book>
        <title>Mon Titre</title>
        <author>
            <name>Tolkien</name>
            <firstname>J R R</firstname>
        </author>
        <gender>Fantasy</gender>
        <pubDate>
            <Day>5</Day>
            <Month>5</Month>
            <Year>1945</Year>
        </pubDate>
    </book>
    <book>
        <title>Mon Titre 2</title>
        <author>
            <name>Tolkien</name>
            <firstname>J R R</firstname>
        </author>
        <gender>Fantasy</gender>
        <pubDate>
            <Day>5</Day>
            <Month>5</Month>
            <Year>1945</Year>
        </pubDate>
    </book>
</books>
